#' @name 03_artificial_distribution_maps.R
#' @date 29.08.2025
#' @author Lisa Bald
#' @contact bald@staff.uni-marburg.de
#' 
#' @description
#' This script creates artificial species distribution maps. 
#' Artificial maps are generated by combining the true species 
#' distributions with Gaussian random fields of varying spatial 
#' autocorrelation.


# ================================================================ #
# 1. Load required packages ----
# ================================================================ #

library(dplyr)            # data manipulation
library(sf)               # spatial vector data
library(parallel)         # parallel processing
library(RandomFields)     # Gaussian random fields
library(NLMR)             # neutral landscape models
library(terra)            # raster handling
library(climateStability) # rescaling to [0,1]
library(RandomFieldsUtils)# dependency RandomField package
library(raster)           # dependency RandomField package

# ================================================================ #
# 2. Configure RandomFields settings ----
# ================================================================ #
RandomFields::RFoptions(cPrintlevel = 0,
                        spConform = FALSE,
                        install = "no",
                        seed = NULL)


# ================================================================ #
# 3. Set working directory and number of cores ----
# ================================================================ #

if (Sys.info()[[4]]=="PC19674") {
  nCores=1
} else if (Sys.info()[[4]]=="pc19543") {
  nCores=1
}

# Unique identifier for this specific configuration
nameRun <- paste0("resultsMain")

# ================================================================ #
# 4. Define experimental evaluation setup ----
# ================================================================ #

# Check if the setup file already exists to ensure consistency across runs.
# If it doesn't exist, we create the full experimental design matrix.
if(!file.exists(paste0("data/",nameRun,"/maps_cor.RDS"))){
  # Create a full list of maps needed: this generates every possible combination 
  # of the variables listed below (Size x Species x Points x Replicates x TestData).
  df=expand.grid(size=as.character(c("KNNDM","random","block1","block2","clusters")) , # data separation strategies
                 species=c("VS01", "VS02", "VS03", "VS04", "VS05", "VS06", "VS07", "VS08", "VS09", "VS10"), # virtual species IDs
                 points=unique(sapply(strsplit(gsub(".gpkg", "", 
                                                    list.files("data/virtualSpeciesTrain", 
                                                               full.names = FALSE,pattern=".gpkg")), "_"), `[`, 2)), # number of originally sampled points points
                 replicates=1:5, # replicate runs
                 model=as.character(c("NA")), # placeholder (no models trained here)
                 testData = 1:6            ) # test dataset identifiers
  

  # Assign a random score (0 to 1) to each combination describing the 
  # agreement with real probability of occurence we want to achieve.
  # we want similar number of "good" and "bad" performing maps.
  df$goodnessOfFit <- sample(seq(0,1,0.01),nrow(df), replace=T)
  # Sort the dataframe by the goodnessOfFit score and reset the row indices
  df=df %>% arrange(goodnessOfFit)
  rownames(df) <- 1:nrow(df)
  saveRDS(df, paste0("data/",nameRun,"/maps_cor.RDS"))
  # If the file already exists, simply load the previous setup to maintain continuity
} else df=readRDS(paste0("data/",nameRun,"/maps_cor.RDS"))
# Final check of the data distribution
plot(table(df$goodnessOfFit))

# ================================================================ #
# 5. Artificial species distribution map generation (cannot be run in parallel) ----
# ================================================================ #

# load environmental variables
vars_path=normalizePath("data/variables.tif")


mclapply(1:nrow(df), function(i){
  
  print(paste("Processing iteration:", i))
  # data loading
  vars=terra::rast(vars_path)
  vs=sf::read_sf(paste0("data/virtualSpeciesTrain/",as.character(df$species[i]),"_",as.character(df$points[i]),"_",df$replicates[i],".gpkg"))
  # Subset the test data based on the chosen spatial sampling strategy (e.g., KNNDM or random)
  test <- vs %>%
    dplyr::filter(.data[[as.character(df$size[i])]] == df$testData[i])
  
  # Quality Control: Skip this iteration if there are fewer than 2 presence points in the test set
  if(nrow(test%>%dplyr::filter(Real==1))<2) return(NULL)
  
  # Load the real species distribution
  realDistribution=terra::rast(paste0("data/virtualSpecies/",as.character(df$species[i]),".tif"))
  
  # ================================================================ #
  # 5a. Generate artificial prediction maps ----
  # ================================================================ #
  
  # Only generate the map if it doesn't already exist
  if(!file.exists(paste0("data/",nameRun,"/maps/",as.character(df$species[i]),"_",df$size[i],"_",df$model[i],"_testData",df$testData[i],"_points",as.character(df$points[i]),"_replicates",df$replicates[i],".tif"))){
    if(!dir.exists(paste0("data/",nameRun,"/maps"))) dir.create(paste0("data/",nameRun,"/maps"),recursive=T)
    
    # Simulate a Gaussian Random Field (GRF) to introduce spatial noise.
    # The 'autocorrRange' determines how "clumpy" or "smooth" the noise is.
    autocorrRange=sample(c(20,50,100,500,800),size=1)
    randomField=nlm_gaussianfield(nrow=1777, ncol=2247, resolution=813.3488,
                                  autocorr_range = autocorrRange)
    
    # Align the Random Field with the real distribution's spatial metadata (Extent, CRS, Mask)
    randomField=terra::rast(randomField)
    terra::ext(randomField) <- terra::ext(realDistribution)
    terra::crs(randomField)<- terra::crs(realDistribution)
    randomField=terra::mask(randomField, realDistribution)
    
    # Create a weighted mixture:
    # 'randomEffects' (from df$goodnessOfFit) acts as the mixing weight.
    # Higher goodnessOfFit = more "Real Distribution", lower = more "Random Noise".
    randomEffects <-df$goodnessOfFit[i]
    x1 <-( randomEffects * realDistribution)
    x2 <- ((1-randomEffects) * randomField)
    pred <- x1 + x2
    
    # Iterative Correction Loop:
    # This loop fine-tunes the weights (x and y) until the actual correlation between 
    # the new map and the truth matches the target 'goodnessOfFit' value within 0.02.
    # This ensures that "good" and "bad" maps are really evenly distributed. 
    trueCor <- terra::layerCor(terra::rast(list(pred,realDistribution)),fun="cor")$correlation[[1,2]]
    
    if(randomEffects != 0){
      if (round(abs(trueCor-randomEffects),2) >= 0.02){
        x=1
        y=1
        if(trueCor > randomEffects){
          while(round(abs(trueCor-randomEffects),2) >= 0.02){
            x1 <-( randomEffects * realDistribution *y)
            x2 <- ((1-randomEffects) * randomField *x)
            pred <- x1 + x2
            trueCor <- terra::layerCor(terra::rast(list(pred,realDistribution)),fun="cor")$correlation[[1,2]]
            x <- x+0.01
            y <- y-0.01
            print(trueCor)
            if(trueCor < 0) break
          }
        }
        if(trueCor < randomEffects){
          while(round(abs(trueCor-randomEffects),2) <= 0.02){
            x1 <-( randomEffects * realDistribution *y)
            x2 <- ((1-randomEffects) * randomField *x)
            pred <- x1 + x2
            trueCor <- terra::layerCor(terra::rast(list(pred,realDistribution)),fun="cor")$correlation[[1,2]]
            x <- x-0.01
            y <- y+0.01
            print(trueCor)
            if(trueCor < 0) break
          }
        }
      }
    }
    print(paste("Random effect is:",randomEffects,". Correlation is:", round(trueCor,2)))
    
    #Rescale values to 0-1 range and write to disk
    pred=climateStability::rescale0to1(pred) # normalize to [0,1]
    terra::writeRaster(pred, paste0("data/",nameRun,"/maps/",as.character(df$species[i]),"_",df$size[i],"_",df$model[i],"_testData",df$testData[i],"_points",as.character(df$points[i]),"_replicates",df$replicates[i],".tif"))
  } else pred=terra::rast(paste0("data/",nameRun,"/maps/",as.character(df$species[i]),"_",df$size[i],"_",df$model[i],"_testData",df$testData[i],"_points",as.character(df$points[i]),"_replicates",df$replicates[i],".tif"))
  
},mc.cores=nCores)


